services:
  postgres:
    image: postgres:17
    container_name: vdevs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - vdevs-postgres-data:/var/lib/postgresql/data

volumes:
  vdevs-postgres-data: